### ISSUE TITLE
Is it possible to unconstrain strscan or fallback if not available?

### ISSUE THREAD

**Issue by adsr** [ruby/rexml#132]
Hello, as I understand it, strscan is a standard gem which means Ruby will always include some version of it. One can update the version via gem, but then it must be compiled on the target system as it isn't provided as a binary gem. ~Recent versions of strscan seem to require a Ruby compiled with libonig support[1], which may not be available. If I'm understanding all of this correctly, this effectively limits the kinds of Ruby installs where rexml can be used.~ (EDIT: I misinterpreted log output. libonig is optional. As mentioned [here](https://github.com/ruby/rexml/issues/131), workarounds include ensuring `build-essential` is installed (gcc and make) or using an earlier version of rexml as mentioned below.)

If your gem directly requires rexml, the easiest way to get around this is to require an earlier version of rexml that doesn't use strscan (e.g., 3.2.6). This isn't a great solution as we miss out on updates. And if rexml is further down the dependency chain, even this may not be viable.

* Does rexml need to constrain the version of strscan? Could we leave it unpinned for better compatibility? (Potentially related to 372daf1a1c93b0a47d174d85feb911d63b501665)
* If the version constraint is needed, can rexml fallback to the old routines if the correct strscan version is unavailable? (or something that uses an earlier version of strscan?)

Apologies if I'm off the mark. By no means a Ruby expert.

~[1] https://github.com/ruby/strscan/blob/ca66d48c47d2b17753a660c628606f0bf788d594/ext/strscan/extconf.rb#L5-L6~

**Comment by adsr** [comment]
Sorry, just saw https://github.com/ruby/rexml/issues/131 which is exactly what prompted this issue on our end. Feel free to close, but I'm still curious about the questions I raised. Thanks.

**Comment by kou** [comment]
> Does rexml need to constrain the version of strscan? Could we leave it unpinned for better compatibility?

@naitoh Can we use old strscan? See also: https://github.com/ruby/rexml/pull/105#discussion_r1451192655

**Comment by kou** [comment]
I've implemented this.

**Comment by naitoh** [comment]
> > Does rexml need to constrain the version of strscan? Could we leave it unpinned for better compatibility?
> 
> @naitoh Can we use old strscan? See also: [#105 (comment)](https://github.com/ruby/rexml/pull/105#discussion_r1451192655)

@kou 

I fixed the problem with `StringScanner#captures` at https://github.com/ruby/strscan/pull/72.

So you will need to use StringScanner that incorporates this fix, but I think f1df7d13b3e57a5e059273d2f0870163c08d7420 should be fine.
Thank you!

However, I am concerned about the impact of the https://github.com/ruby/strscan/pull/79 modification on JRuby, is that a problem?

See: https://github.com/ruby/rexml/pull/105/files#r1451192655

**Comment by kou** [comment]
I think that JRuby users can use the latest strscan or upgrade JRuby itself. strscan gem for JRuby is a fat gem. So JRuby users don't need to use build it.

**Comment by naitoh** [comment]
@kou 
> I think that JRuby users can use the latest strscan or upgrade JRuby itself. strscan gem for JRuby is a fat gem. So JRuby users don't need to use build it.

OK.
I see.
Thanks!
