### ISSUE TITLE
Question on the next published Gem version after 3.2.8

### ISSUE THREAD

**Issue by tmahn** [ruby/rexml#137]
Hello folks, sorry if this is not the right place for this, but i had a question on when you will be publishing the next version?  There is a change / fix in the current master branch we would like to have applied to our code base.

basically wondering if we should spend time porting the fix to a local version of this gem or just wait until the next published version? 

thanks!

**Comment by kou** [comment]
We'll release a new version in a few weeks.

**Comment by kou** [comment]
Done.
