### ISSUE TITLE
Backporting recent CVE fixes to 3.2.x branch

### ISSUE THREAD

**Issue by robertfall** [ruby/rexml#179]
As with many other folks we've picked up the recent CVE and tried to fix it, but run into issues with transitive dependencies.

We have a dependency chain that includes `activemerchant` that hasn't updated their dependency on `rexml` yet and it would be helpful if we could mitigate the CVE without needing to bump the minor version of the rexml (because of version restrictions).

I took a look at the changes but they seem spread across multiple different files and features and I couldn't make a call about how difficult back-porting the fix would be.

**Comment by kou** [comment]
Sorry.
We don't have 3.2.x branch. We aren't maintaining multiple release branches. We have only one active branch (master).
