### ISSUE TITLE
`test_linear_performance_percent_gt` is flaky results with Ruby 3.1

### ISSUE THREAD

**Issue by hsbt** [ruby/rexml#185]
From https://github.com/ruby/ruby/pull/11172#issuecomment-2230286105

I found `test_linear_performance_percent_gt` is failed sometimes with Ruby 3.1 and REXML 3.3.2.

* https://github.com/ruby/actions/actions/workflows/snapshot-ruby_3_1.yml
* https://github.com/ruby/actions/actions/runs/10022301424/job/27701976765#step:17:180

I'm not sure we should relax that limit for Ruby 3.1. Could you give the idea for that?

**Comment by kou** [comment]
It seems that Ruby 3.1 uses `tool/lib/core_assertions.rb`  not test-unit-ruby-core:

https://github.com/ruby/actions/actions/runs/10022301424/job/27701976765#step:17:185

```text
  /home/runner/work/actions/actions/snapshot-ruby_3_1/tool/lib/core_assertions.rb:757:in `block (2 levels) in assert_linear_performance'
```

Can we use test-unit-ruby-core with Ruby 3.1 too?

**Comment by kou** [comment]
test-unit-ruby-core doesn't have the https://github.com/ruby/ruby/blob/ruby_3_1/tool/lib/core_assertions.rb#L757 assertion.
If we can use test-unit-ruby-core (only) for bundled gem tests, we will be able to fix this problem.

**Comment by hsbt** [comment]
I merged `assert_linear_performance` changes at https://github.com/ruby/ruby/pull/11581. It may resolved this flaky result.
