### ISSUE TITLE
ParseException on 3.3.3

### ISSUE THREAD

**Issue by msxavi** [ruby/rexml#211]
Hi there,

Before `3.3.3` I was able to access an invalid SamlResponse e.g: 
```ruby
 response ||= OneLogin::RubySaml::Response.new(
    "invalid",
    :settings => @config.saml_settings,
    :allowed_clock_drift => 60,
    :skip_subject_confirmation => true
  )

 response.name_id # returns nil on 3.3.2 and ruby-saml 1.17.0
```

On `3.3.3` all the way to `3.3.8`,  `ParseException` is now raised:

```ruby
     REXML::ParseException:
       Malformed XML: Content at the start of the document (got 'invalid')
       Line: 1
       Position: 7
       Last 80 unconsumed characters:
     # /usr/local/bundle/gems/rexml-3.3.3/lib/rexml/parsers/baseparser.rb:487:in `pull_event'
     # /usr/local/bundle/gems/rexml-3.3.3/lib/rexml/parsers/baseparser.rb:218:in `pull'
     # /usr/local/bundle/gems/rexml-3.3.3/lib/rexml/parsers/treeparser.rb:22:in `parse'
     # /usr/local/bundle/gems/rexml-3.3.3/lib/rexml/document.rb:448:in `build'
     # /usr/local/bundle/gems/rexml-3.3.3/lib/rexml/document.rb:101:in `initialize'
     # /usr/local/bundle/gems/ruby-saml-1.17.0/lib/xml_security.rb:191:in `initialize'
```

TIA.

**Comment by kou** [comment]
This is an intentional fix.

XML processors must report non well-formed violations:

https://www.w3.org/TR/2006/REC-xml11-20060816/#proc-types

> Validating and non-validating processors alike MUST report violations of this specification's well-formedness constraints in the content of the [document entity](https://www.w3.org/TR/2006/REC-xml11-20060816/#dt-docent) and any other [parsed entities](https://www.w3.org/TR/2006/REC-xml11-20060816/#dt-parsedent) that they read.

**Comment by msxavi** [comment]
@kou Sure, my point is that it doesn't look like a patch fix if that causes backward incompatibilities.

**Comment by kou** [comment]
REXML doesn't use semantic versioning.
