### ISSUE TITLE
New maintainer: naitoh

### ISSUE THREAD

**Issue by kou** [ruby/rexml#225]
@naitoh has been an active contributor to REXML: https://github.com/ruby/rexml/commits?author=naitoh

Currently, I'm the only maintainer of REXML. If we have multiple maintainers of REXML, we'll be able to make REXML more sustainable.

Maintainer tasks:
* Triage issues
* Fix issues
* Review PRs
* Improve REXML
* Release new versions (I prepared Trusted Publishing. We just need to prepare a release note, run `rake release` for tagging and bumping version after a new release.)
* Triage security vulnerability reports
* Fix security vulnerabilities
* ...

@naitoh Are you interesting in becoming a maintainer of REXML?

**Comment by naitoh** [comment]
@kou 
Yes, I would like to become a maintainer of REXML.

**Comment by kou** [comment]
Thanks!

@hsbt Could you invite @naitoh to the `rexml-admin` team?
It seems that I can't invite  people who don't a member of the `ruby` organization.

**Comment by hsbt** [comment]
I send an invitation now 🚀

**Comment by naitoh** [comment]
I have joined the `rexml-admin` team!
Thanks!
