### ISSUE TITLE
Use bundled rexml for Ruby 2.4, 2.5, 2.6 and 2.7

### ISSUE THREAD

**Issue by yahonda** [ruby/rexml#28]
Based on the discussion at https://github.com/googleapis/google-api-ruby-client/issues/871

I'm wondering if it is "safe" to use bundled rexml gem for Ruby 2.4, 2.5, 2.6 and 2.7.

### Background:

If some of Ruby gems which support multiple version of Ruby from 2.4 and Ruby 2.8 (maybe 3), it needs to gemfile to `Gemfile` or `spec.add_runtime_dependency` to gemspec files to use rexml for Ruby 2.8. 

As far as I know, RubyGems does not have a feature to enable `add_runtime_dependency` for the specific version of Ruby then all of Ruby versions will use bundled rexml gem.

**Comment by hsbt** [comment]
@kou Should we add the `required_ruby_version` with Ruby 2.4 to gemspec?

**Comment by kou** [comment]
We support maintained Ruby versions.
So it's safe to use REXML with Ruby >= 2.4. :-)

@hsbt I don't think that we need to add `require_ruby_version` because we don't need to care about EOL-ed Rubies.
