### ISSUE TITLE
REXML gem specifies ruby > 0 but does not support < 2

### ISSUE THREAD

**Issue by alextwoods** [ruby/rexml#38]
Since rexml has been [moved from a default to a bundled gem in Ruby 3.0](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/),  we are working on adding it as an explicit dependency for the [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby/pull/2457).  However, adding it as a dependency breaks in Ruby 1.9.3 (anything < 2) because some of the code uses syntax that is incompatible with 1.9 (example [commit](https://github.com/ruby/rexml/commit/811a5f9bd827b9f4d3a8f2b1b2198fd5b09dca21) where incompatibility was introduced).  

Would it be possible to either: 
1) Specify supported ruby versions in the gemspec or
2) Fix the syntax (use of the double splat) to ensure compatability

**Comment by mullermp** [comment]
@hsbt @kou @nurse Any opinion or recommendation on this? The AWS SDK unfortunately still supports Ruby 1.9.3.

**Comment by hsbt** [comment]
There is no good solution yet. Because solution.1 is not resolve this issue. The current `Gem::Specification` didn't have ruby version selector for runtime dependency.

Unfortunately, We can choose only solution.2.

**Comment by mullermp** [comment]
My understanding is that (following this [commit](https://github.com/ruby/rexml/commit/811a5f9bd827b9f4d3a8f2b1b2198fd5b09dca21)) we can simply change `XPathParser` to be initialized with `XPathParser.new(options)` and change the definition to be something like:

```
def initialize(options = {})
   ...
  @strict = options[:strict] || false
end
```

Would you agree? If you're able to handle this, I can leave it to you, otherwise, we're happy to create a starter PR, hopefully there isn't other code that needs these kinds of changes..

**Comment by kou** [comment]
Does REXML 3.1.7.3 work on Ruby 1.9.3?

BTW, why do you want to support Ruby 1.9.3?

**Comment by kou** [comment]
You'll be able to disable gemified REXML on Ruby 1.9.3 by the following change:

```diff
diff --git a/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser.rb b/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser.rb
index 72b43b26d..dd11a527e 100644
--- a/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser.rb
+++ b/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser.rb
@@ -82,7 +82,7 @@ module Aws
 
         def try_load_engine(name)
           load_engine(name)
-        rescue LoadError
+        rescue LoadError, SyntaxError
           false
         end
 
```

**Comment by kou** [comment]
Or you will be able to force using system REXML on Ruby 1.9.3:

```diff
diff --git a/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/rexml.rb b/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/rexml.rb
index e491364df..1154094de 100644
--- a/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/rexml.rb
+++ b/gems/aws-sdk-core/lib/aws-sdk-core/xml/parser/engines/rexml.rb
@@ -1,7 +1,13 @@
 # frozen_string_literal: true
 
+use_system_rexml = ((RUBY_VERSION <=> "2.0.0") < 0)
+if use_system_rexml
+  require "rbconfig"
+  $LOAD_PATH.unshift(RbConfig::CONFIG["rubylibdir"])
+end
 require 'rexml/document'
 require 'rexml/streamlistener'
+$LOAD_PATH.shift if use_system_rexml
 
 module Aws
   module Xml
```

**Comment by mullermp** [comment]
>BTW, why do you want to support Ruby 1.9.3?

We're unfortunately committed to doing so, by some stakeholders, as well as our maintenance policy which suggests we should only drop runtime versions in our next SDK major version.

As far as your suggestions, thank you for providing those! We will try these shortly.

**Comment by alextwoods** [comment]
Using the oldest published rexml (3.1.7.3) does not work and gives the same errors:
```ruby
SyntaxError: /usr/share/rvm/gems/ruby-1.9.3-p551/gems/rexml-3.1.7.3/lib/rexml/xpath.rb:34: syntax error, unexpected tPOW, expecting ')'
      parser = XPathParser.new(**options)
                                 ^
```

The first of @kou proposed changes (adding SyntaxError to the exceptions that are caught) may break existing customers that were relying on rexml as their xml engine.  However, the second change (using system rexml for ruby <2) does work and is backwards compatible.  

However, the question for me is whether that is the right change to make, or if we should ensure that rexml supports the rubies that its gemspec defines (ie, all of them).  I'm not a big fan of using old syntax to ensure support for EOL rubies, but because the gemspec never specified rubies, I'd argue for using the older syntax in rexml to ensure support and if future breaking changes are made, setting the minimum ruby version in the gemspec.

**Comment by alextwoods** [comment]
As an update here:  we have decided to not add an explicit dependency on rexml and add the patch to use system rexml for Ruby version < 2, since many other gems, eg [crack](https://github.com/jnunemaker/crack/commit/c61172bf32e1769748fded156c2f2fc03dac69c1)) are adding explicit dependencies.  

It looks like there are other unreleased changes in master (ie: #37 ) that further break compatability with older rubies.  I'd recommend updating the gemspec to specify the minimum supported ruby version (with the use of `refine` I believe that now would be 2.1).

**Comment by kou** [comment]
We don't want to care about EOL-ed Rubies to reduce maintenance cost.
We'll add Ruby version constrain explicitly if we drop support for not EOL-ed Rubies.

It's better that we improve RubyGems to add support for specifying dependencies for each Ruby version. It'll be useful for a similar case in the future.
Python's pip support it: https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

If you're interested in the improvement, could you open an issue at https://github.com/rubygems/rubygems/issues ?

**Comment by mullermp** [comment]
>We don't want to care about EOL-ed Rubies to reduce maintenance cost.

I totally agree with this. However, shouldn't we work within the current limitations of gemspecs, and shouldn't the gemspec be reliable? Any user of Ruby 1.9 or 2.0 would not receive an error on gem install. If rexml is included with stdlib up until Ruby 3, could we not declare that this gem requires Ruby >= 3?

**Comment by kou** [comment]
> Any user of Ruby 1.9 or 2.0

We don't want to care about EOL-ed Rubies...

> could we not declare that this gem requires Ruby >= 3?

We can use this with all maintained Rubies such as Ruby 2.7.

**Comment by coding-bunny** [comment]
Right,
so because of this decision, we cannot build several legacy projects anymore because `rexml` decided to go this approach...

**Comment by kou** [comment]
I don't understand what you want to say...
Why do these legacy projects use Ruby 3.0 or later? Ruby < 3.0 still bundles REXML. These legacy projects can use REXML without rexml gem dependency.

**Comment by alextwoods** [comment]
While Ruby < 3 still bundles REXML, projects that support a range of rubies are broken.  If a project/Gemfile needs to support a wide range of rubies (as we do with the AWS SDK for example), we cannot include rexml as an explicit dependency (Because it breaks on old rubies), but users with Ruby 3+ are then broken and need to explicitly include rexml.  

I'd still argue for updating the minimum required version of ruby (2.1) in rexml's gemspec - this will ensure that the library will not get installed for users of unsupported rubies.

**Comment by mullermp** [comment]
Agree with @alextwoods. You might be able to go a step further and say it can only be installed with Ruby 3+ as it is bundled with versions prior.

**Comment by kou** [comment]
Why do the AWS SDK developers ignore RubyGems improvement suggestion mentioned at https://github.com/ruby/rexml/issues/38#issuecomment-755793581?
