### ISSUE TITLE
Unprotect "gem push"

### ISSUE THREAD

**Issue by kou** [ruby/rexml#4]
@hsbt https://rubygems.org/gems/rexml says "This namespace is reserved by rubygems.org.". What should we do to unprotect it?

**Comment by hsbt** [comment]
@kou We need to remove `rexml` from the blacklist of rubygems.org at https://github.com/rubygems/rubygems.org/blob/master/lib/patterns.rb#L65.

I will send a patch for removing default gems contained `rexml` later.

**Comment by kou** [comment]
Thanks!

**Comment by hsbt** [comment]
I did submit patch to rubygems.org: https://github.com/rubygems/rubygems.org/pull/1775

**Comment by hsbt** [comment]
@kou I released the current master branch as v3.1.7.3. https://rubygems.org/gems/rexml It needs to reserve namespace of rexml.

And, I added you to owners of rexml gem. Please consider releasing 3.1.8 or 3.x.y for stable version.
