### ISSUE TITLE
Unreleased rexml 3.1.9.1 is shipped by Ruby 2.6.8

### ISSUE THREAD

**Issue by headius** [ruby/rexml#79]
Ruby 2.6.8 ships with what it reports as rexml 3.1.9.1:

```
$ ruby -rrexml/rexml -e "p REXML::VERSION"
"3.1.9.1"
```

This version does not exist on rubygems.org and does not appear to have been released. This prevents JRuby from shipping it, since we source **all** gem-based standard libraries from released gems.

Could we get this released, please? 😀

**Comment by kou** [comment]
OK. I'll do.

Background: We released Ruby 2.6.8 because REXML in Ruby 2.6.7 has a vulnerability. The fix of the vulnerability for Ruby 2.6.7 is backported only in the Ruby repository. It's not applied to this repository. The master branch was only updated.

**Comment by headius** [comment]
@kou Thank you!
