### ISSUE TITLE
Unicode noncharacters

### ISSUE THREAD

**Issue by fmang** [ruby/rexml#81]
As of the current master (fc94069, near 3.2.6), REXML rejects Unicode noncharacters like U+FFFF :

```
2.7.1 :001 > require "rexml/document"
 => true 
2.7.1 :002 > REXML::Document.new("&#x03B1;").text
 => "α" 
2.7.1 :003 > REXML::Document.new("&#xFFFF;").text
Traceback (most recent call last):
        9: from /usr/share/rvm/rubies/ruby-2.7.1/bin/irb:23:in `<main>'
        8: from /usr/share/rvm/rubies/ruby-2.7.1/bin/irb:23:in `load'
        7: from /usr/share/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        6: from (irb):3
        5: from (irb):3:in `new'
        4: from /home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/document.rb:101:in `initialize'
        3: from /home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/document.rb:448:in `build'
        2: from /home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/parsers/treeparser.rb:21:in `parse'
        1: from /home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/parsers/treeparser.rb:96:in `rescue in parse'
REXML::ParseException (#<RuntimeError: Illegal character "&#xFFFF;" in raw string "&#xFFFF;">)
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/text.rb:163:in `block in check'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/text.rb:155:in `scan'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/text.rb:155:in `check'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/text.rb:122:in `initialize'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/parsers/treeparser.rb:47:in `new'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/parsers/treeparser.rb:47:in `parse'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/document.rb:448:in `build'
/home/frederic/.rvm/gems/ruby-2.7.1/gems/rexml-3.2.6/lib/rexml/document.rb:101:in `initialize'
...
Illegal character "&#xFFFF;" in raw string "&#xFFFF;"
Line: 1
Position: 8
Last 80 unconsumed characters:
```

It looks like noncharacters are voluntarily excluded, according to <https://github.com/ruby/rexml/blob/fc94069641019fd7627a0a621032c51a268998d1/lib/rexml/text.rb#L50>.

However, Unicode standard 14.0.0, section 23.7 « Noncharacters » (<https://www.unicode.org/versions/Unicode14.0.0/ch23.pdf#G12612>) states:

> Applications are free to use any of these noncharacter code points internally. They have no
> standard interpretation when exchanged outside the context of internal use. However, they
> are not illegal in interchange, nor does their presence cause Unicode text to be ill-formed.

I believe REXML should therefore not forbid these noncharacters, and even forbid as few characters as possible. The current restrictions are limiting for using REXML as a neutral carrier to transmit arbitrary Unicode strings.

Best regards.

**Comment by kou** [comment]
The XML specification https://www.w3.org/TR/xml/#charsets rejects the characters:

> Char ::= | #x9 \| #xA \| #xD \| [#x20-#xD7FF] \| [#xE000-#xFFFD] \| [#x10000-#x10FFFF] | /* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

**Comment by fmang** [comment]
I see. Thanks for pointing it out!

It looks like the XML specification is based on Unicode 5.0.0, according to <https://www.w3.org/TR/xml/#sec-existing-stds>. 

It also happens Unicode 5.0.0 is way less tolerant than 14.0.0 regarding noncharacters, stating in <https://www.unicode.org/versions/Unicode5.0.0/ch16.pdf>:

> Applications  are  free  to  use  any  of  these  noncharacter  code  points  internally  but  should  
> never  attempt  to  exchange  them.  If  a  noncharacter  is  received  in  open  interchange,  an  
> application is not required to interpret it in any way.

Now, while REXML is compliant to the XML standard, it’s unfortunate that it rejects noncharacters even though it could easily support them, because real-world XML generators may emit those characters. I wonder how reasonable it would be to add a lax mode to the REXML parser, and apply Postel’s law?

**Comment by kou** [comment]
Do you have any real-world example for it?

> I wonder how reasonable it would be to add a lax mode to the REXML parser, and apply Postel’s law?

I'm neutral for it.

BTW, if we like Postal's law, real-world XML generators should not send any character that is rejected by the XML specification. :-)

**Comment by fmang** [comment]
My use case here is WinRM transmitting the result of a script that outputted U+FFFF. It looks like its protocol is SOAP-based, so the U+FFFF gets serialized into XML. It’s not like the script was meant to output such a character, but it transmits values it found in the Windows registry and, misery! the registry contained a weird value.

**Comment by kou** [comment]
How about changing the script to encode the output in BASE64 or something? Then the output can contain only safe characters.

**Comment by fmang** [comment]
That would work indeed, but wrapping every PowerShell command I run into
a base64 encoder sounds complicated compared to, say, patching REXML to
allow skipping the character validation. The simpler the better!

**Comment by kou** [comment]
OK.
It seems that your use case isn't generic. It'll be better that this case is resolved by patching your REXML as you said.

**Comment by fmang** [comment]
Alright! Thank you for considering the feature.
