### ISSUE TITLE
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by juanxupalaci** [ruby/rexml#85]
I have this error:

rexml/text.rb:133:in `=~': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)

Has it happened to someone?, Regards

**Comment by kou** [comment]
Could you provide a script (and needed data) to reproduce this?

**Comment by albanpeignier** [comment]
We're experiencing the same issue with non UTF-8 files parsed with https://github.com/soulcutter/saxerator.

In this case, `REXML::Element` is used with non-UTF-8 strings, and a regexp used into `Text::unnormalize` requires an UTF-8 encoding:

``` ruby
require 'rexml/document'

element = REXML::Element.new('test')
element.add_text("Norrlandsvägen".encode('iso-8859-1'))

puts element.get_text.value
```

Gives this error:

```
Traceback (most recent call last):
        3: from tmp/test.rb:6:in `<main>'
        2: from /usr/lib/ruby/2.7.0/rexml/text.rb:251:in `value'
        1: from /usr/lib/ruby/2.7.0/rexml/text.rb:394:in `unnormalize'
/usr/lib/ruby/2.7.0/rexml/text.rb:394:in `gsub': incompatible encoding regexp match (UTF-8 regexp with ISO-8859-1 string) (Encoding::CompatibilityError)
```

In our case, we've supposed that REXML only supports UTF-8 text (and we're working to convert text manipulated by Saxerator).

**Comment by kou** [comment]
Yes.
REXML supports parsing non-UTF-8 XML but REXML uses UTF-8 string as internal string. (REXML converts non-UTF-8 strings in the parsed XML to UTF-8 strings.)
So users  need to pass a UTF-8 string to `REXML::Element#add_text`.

**Comment by albanpeignier** [comment]
For me, this issue can be fixed. Thanks for your quick answer.
